name: Tag new version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Tagging Composite Action
        uses: ./.github/actions/tagging-action